package highlighters

import (
	"github.com/DeeStarks/lime/internal/utils"
	"github.com/gdamore/tcell/v2"
)

var (
	golang_comment_indicator = "//"
	// Highlighters is a map of highlighters
	golang_scheme = map[string]tcell.Style{
		"func":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"var":         utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"const":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"type":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"struct":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"interface":   utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"package":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"import":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"return":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"break":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"continue":    utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"goto":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"fallthrough": utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"if":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"else":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"for":         utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"range":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"switch":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"case":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"default":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"select":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"defer":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"go":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		":=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"=":           utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"!=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"==":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"<":           utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		">":           utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"<=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		">=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"+=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"-=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"*=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"/=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"%=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"&=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"|=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"^=":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"<<=":         utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		">>=":         utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"&&":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"||":          utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"*":           utils.CreateStyle(tcell.ColorBlack, tcell.ColorPurple),
		"&":           utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),

		"(": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		")": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		"{": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		"}": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		"[": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		"]": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),
		";": utils.CreateStyle(tcell.ColorBlack, tcell.ColorYellow),

		"int":        utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"string":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"bool":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"float64":    utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"float32":    utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uint":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uint8":      utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uint16":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uint32":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uint64":     utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"uintptr":    utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"byte":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"rune":       utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"complex64":  utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),
		"complex128": utils.CreateStyle(tcell.ColorBlack, tcell.ColorBlue),

		"true":  utils.CreateStyle(tcell.ColorBlack, tcell.ColorSkyblue),
		"false": utils.CreateStyle(tcell.ColorBlack, tcell.ColorSkyblue),
		"nil":   utils.CreateStyle(tcell.ColorBlack, tcell.ColorSkyblue),
		"iota":  utils.CreateStyle(tcell.ColorBlack, tcell.ColorSkyblue),
	}
)
